# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build with Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          GITHUB_USER: ${{ secrets.USER }}
        run: |
          docker run --rm -e GITHUB_TOKEN=${GITHUB_TOKEN} -e GITHUB_USER=${GITHUB_USER} -e REPO_NAME=http-requests tomoncle/github-workflow /build/startup.sh
          docker rmi tomoncle/github-workflow
